version: '3.8'

services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads
      - ./app:/app/app
    environment:
      - PYTHONPATH=/app
      - ENVIRONMENT=development
    restart: unless-stopped
    
  # Future services can be added here:
  # database:
  #   image: postgres:15
  #   environment:
  #     POSTGRES_DB: logsage
  #     POSTGRES_USER: logsage
  #     POSTGRES_PASSWORD: logsage_password
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
  
  # vector_db:
  #   image: qdrant/qdrant:latest
  #   ports:
  #     - "6333:6333"
  #   volumes:
  #     - qdrant_data:/qdrant/storage

# volumes:
#   postgres_data:
#   qdrant_data: